const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');

function readText(filePath) {
  return fs.readFileSync(path.join(root, filePath), 'utf8');
}

function markdownFiles(dir) {
  return fs.readdirSync(path.join(root, dir), { withFileTypes: true })
    .flatMap((entry) => {
      const name = path.join(dir, entry.name);
      return entry.isDirectory() ? markdownFiles(name) : [name];
    })
    .filter((name) => name.endsWith('.md'))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
}

function parseStoryTitle(content, fallbackId) {
  const firstHeading = content.match(/^#\s+เรื่องที่\s+(\d+):\s+(.+?)\s+\((.+?)\)\s*$/m);
  if (firstHeading) {
    return {
      id: Number(firstHeading[1]),
      title: firstHeading[2].trim(),
      titleTh: firstHeading[3].trim()
    };
  }

  return {
    id: fallbackId,
    title: `Story ${fallbackId}`,
    titleTh: `เรื่องที่ ${fallbackId}`
  };
}

function seriesFromFile(file) {
  const folder = file.split(/[\\/]/)[1] || '';
  const label = folder.replace(/^\d+-/, '');
  const map = {
    'daily-life': ['daily-life', 'ชีวิตประจำวัน'],
    'work-career': ['work', 'การทำงาน'],
    travel: ['travel', 'ท่องเที่ยว'],
    food: ['food', 'อาหาร'],
    relationships: ['relationships', 'ความสัมพันธ์'],
    health: ['health', 'สุขภาพ'],
    education: ['education', 'การศึกษา'],
    career: ['career', 'อาชีพ'],
    technology: ['technology', 'เทคโนโลยี'],
    money: ['money', 'การเงิน'],
    environment: ['environment', 'สิ่งแวดล้อม'],
    culture: ['culture', 'วัฒนธรรม'],
    hobbies: ['hobbies', 'งานอดิเรก'],
    community: ['community', 'ชุมชน'],
    future: ['future', 'อนาคต'],
    communication: ['communication', 'การสื่อสาร'],
    'life-skills': ['life-skills', 'ทักษะชีวิต'],
    world: ['world', 'รอบโลก']
  };
  return map[label] || [label || 'misc', label || 'อื่น ๆ'];
}

function parseStories() {
  return markdownFiles('stories').map((file) => {
    const content = readText(file);
    const fallbackId = Number(file.match(/story-(\d+)\.md$/)?.[1] || 0);
    const { id, title, titleTh } = parseStoryTitle(content, fallbackId);
    const [series, seriesTh] = seriesFromFile(file);
    return { id, title, titleTh, series, seriesTh, file, content };
  }).sort((a, b) => a.id - b.id);
}

function parseVocabulary() {
  return markdownFiles('vocabulary').flatMap((file) => {
    const level = Number(file.match(/level-(\d)/)?.[1] || 0);
    return readText(file).split(/\r?\n/).flatMap((line) => {
      const cells = line.split('|').slice(1, -1).map((cell) => cell.trim());
      if (cells.length !== 5 || !/^\d+$/.test(cells[0])) return [];
      return [{
        level,
        number: Number(cells[0]),
        word: cells[1].replace(/\*\*/g, ''),
        pronunciation: cells[2],
        meaning: cells[3],
        example: cells[4].replace(/\*\*/g, '')
      }];
    });
  }).sort((a, b) => a.number - b.number);
}

function parsePhraseFiles() {
  const categories = {};
  for (const file of markdownFiles('phrases')) {
    let currentKey = null;
    let currentTitle = null;
    for (const line of readText(file).split(/\r?\n/)) {
      const heading = line.match(/^#{2,3}\s+(.+)$/);
      if (heading) {
        currentTitle = heading[1].trim();
        currentKey = currentTitle.toLowerCase().replace(/[^a-z0-9ก-๙]+/g, '-').replace(/^-|-$/g, '');
        categories[currentKey] = categories[currentKey] || { title: currentTitle, items: [] };
        continue;
      }

      const cells = line.split('|').slice(1, -1).map((cell) => cell.trim());
      if (!currentKey || cells.length < 2) continue;
      if (cells.some((cell) => /^-+$/.test(cell))) continue;
      if (['English', 'Idiom'].includes(cells[0])) continue;

      categories[currentKey].items.push({
        en: cells[0].replace(/\*\*/g, ''),
        pronunciation: cells.length >= 3 ? cells[1] : '',
        th: cells.length >= 3 ? cells[2].replace(/\*\*/g, '') : cells[1].replace(/\*\*/g, '')
      });
    }
  }
  return Object.fromEntries(Object.entries(categories).filter(([, category]) => category.items.length));
}

const data = {
  generatedAt: new Date().toISOString(),
  stories: parseStories(),
  vocabulary: parseVocabulary(),
  phrases: parsePhraseFiles()
};

const output = `// Generated by tools/generate-data.js. Do not edit by hand.\n` +
  `const appData = ${JSON.stringify(data, null, 2)};\n` +
  `const stories = appData.stories;\n` +
  `const vocabulary = appData.vocabulary;\n` +
  `const phrases = appData.phrases;\n`;

fs.writeFileSync(path.join(root, 'data.js'), output, 'utf8');
console.log(`Generated data.js: ${data.stories.length} stories, ${data.vocabulary.length} vocabulary, ${Object.values(data.phrases).reduce((sum, category) => sum + category.items.length, 0)} phrases`);
